// pages/PlaybackPerformance.js
import React, { useState } from 'react';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';
import UploadZone from '../components/UploadZone';
import { db } from '../firebase';
import { collection, addDoc, serverTimestamp } from 'firebase/firestore';

const COLORS = { 'NCP+ADK: STB (all)': '#3b82f6', 'ADK 3.0.1': '#1e3a8a', 'ADK 3.1.1': '#f59e0b', 'ADK 3.1.0': '#7c3aed', 'NCP+ADK: PlayStation (all)': '#ec4899', 'NCP+ADK: Xbox (all)': '#10b981' };

function fmt(v) {
  const n = parseFloat(v);
  if (isNaN(n)) return v;
  if (Math.abs(n) >= 1e6) return (n/1e6).toFixed(2) + 'M';
  if (Math.abs(n) >= 1e3) return (n/1e3).toFixed(0) + 'K';
  return n.toFixed(3);
}

export default function PlaybackPerformance() {
  const [data, setData] = useState(null);
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  const [copied, setCopied] = useState(false);

  const onParsed = (rows) => {
    setData(rows);
    setSaved(false);
  };

  const saveToFirestore = async () => {
    if (!data) return;
    setSaving(true);
    try {
      await addDoc(collection(db, 'weeklySnapshots'), {
        type: 'playbackPerformance',
        rows: data,
        uploadedAt: serverTimestamp(),
        weekOf: new Date().toISOString().slice(0, 10),
      });
      setSaved(true);
    } catch (e) { console.error(e); }
    setSaving(false);
  };

  const generateConfluence = () => {
    if (!data) return '';
    const summary = data.slice(0, 4).map(r => Object.entries(r).map(([k,v])=>`${k}: ${v}`).join(' | ')).join('\n');
    return `<h3>Playback Performance (Last 30 Days)</h3>\n<!-- Generated by NCP+ADK KPI App -->\n${summary}`;
  };

  const copy = () => {
    navigator.clipboard.writeText(generateConfluence());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // Derive chart-friendly data from upload
  const chartData = data ? data.slice(0, 30).map((r, i) => ({ day: i + 1, ...r })) : [];
  const numericKeys = data ? Object.keys(data[0] || {}).filter(k => !isNaN(parseFloat(data[0][k])) && k !== 'date').slice(0, 6) : [];

  return (
    <div>
      <div className="section-header">
        <span className="section-badge badge-weekly">Weekly</span>
        <h2 style={{ fontSize: 20, fontWeight: 700, color: '#0f2744' }}>Playback Performance</h2>
      </div>

      <div className="instructions">
        <h4>ℹ️ How to get this data</h4>
        <ol>
          <li>Open the <a href="https://pulse.conviva.com/app/custom-dashboards/dashboard/48643?data-source=ei" target="_blank" rel="noreferrer">Conviva: NCP+ADK Playback Performance Comparisons</a> dashboard.</li>
          <li>Set the date range to <strong>Last 30 days</strong>.</li>
          <li>Click the <strong>Export</strong> button (top right) → select <strong>CSV</strong>.</li>
          <li>Upload the exported CSV below.</li>
        </ol>
        <div style={{ marginTop: 12, display: 'flex', gap: 10, flexWrap: 'wrap' }}>
          <a className="source-link" href="https://pulse.conviva.com/app/custom-dashboards/dashboard/48643?data-source=ei" target="_blank" rel="noreferrer">🔗 Open Conviva Dashboard</a>
        </div>
      </div>

      <div className="card">
        <div className="card-title">Upload Conviva Export</div>
        <div className="card-subtitle">CSV export from "NCP+ADK: Playback Performance Comparisons" — last 30 days</div>
        <UploadZone
          label="Drop Conviva Playback Performance CSV here"
          hint="Export from Conviva → NCP+ADK: Playback Performance Comparisons → last 30 days"
          onParsed={onParsed}
        />
      </div>

      {data && (
        <>
          <div className="alert alert-success">
            ✅ {data.length} rows loaded. Review the charts below, then save to history and copy to Confluence.
          </div>

          {numericKeys.length > 0 && (
            <div className="card">
              <div className="card-title">📊 Chart Preview</div>
              <div className="card-subtitle">Auto-generated from upload · Matches Conviva dashboard layout</div>
              <ResponsiveContainer width="100%" height={280}>
                <LineChart data={chartData} margin={{ top: 5, right: 20, bottom: 5, left: 0 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" />
                  <XAxis dataKey="day" tick={{ fontSize: 11 }} />
                  <YAxis tick={{ fontSize: 11 }} tickFormatter={v => fmt(String(v))} />
                  <Tooltip formatter={(v) => fmt(String(v))} />
                  <Legend wrapperStyle={{ fontSize: 12 }} />
                  {numericKeys.map((k, i) => (
                    <Line key={k} type="monotone" dataKey={k} stroke={Object.values(COLORS)[i % 6]} strokeWidth={2} dot={false} name={k} />
                  ))}
                </LineChart>
              </ResponsiveContainer>
            </div>
          )}

          <div className="card">
            <div className="card-title">📋 Data Preview</div>
            <div style={{ overflowX: 'auto' }}>
              <table className="data-table">
                <thead>
                  <tr>{Object.keys(data[0] || {}).map(k => <th key={k}>{k}</th>)}</tr>
                </thead>
                <tbody>
                  {data.slice(0, 10).map((r, i) => (
                    <tr key={i}>{Object.values(r).map((v, j) => <td key={j}>{v}</td>)}</tr>
                  ))}
                </tbody>
              </table>
              {data.length > 10 && <p className="text-muted" style={{ marginTop: 8 }}>Showing first 10 of {data.length} rows</p>}
            </div>
          </div>

          <div className="card">
            <div className="card-title">🚀 Confluence Output</div>
            <div className="card-subtitle">Copy this block and paste it into the Playback Performance section of the weekly Confluence page.</div>
            <div className="output-preview">{generateConfluence()}</div>
            <div className="output-actions">
              <button className="btn btn-primary" onClick={copy}>{copied ? '✅ Copied!' : '📋 Copy to Clipboard'}</button>
              <button className="btn btn-secondary" onClick={saveToFirestore} disabled={saving || saved}>
                {saved ? '✅ Saved to History' : saving ? <><span className="spinner" /> Saving…</> : '💾 Save to History'}
              </button>
            </div>
          </div>
        </>
      )}
    </div>
  );
}
